### ISSUE TITLE
suggestion for Kinodynamic/forceOrientaion 

### ISSUE THREAD

**Issue by daeunSong** [humanoid-path-planner/hpp-rbprm-corba#37]
hello, 

this is not really an issue but a suggestion for a small improvement. 

As I tried out some scripts in script/scenarios folders, I found out that the parameter "Kinodynamic/forceOrientaion" to force the orientation of the trunk to match the direction of the motion seems like it could be improved.

The orientation of the trunk is trying to follow the exact direction of the motion, which results in failure of contact motion planning, especially when climbing up the stairs.

I think making the orientation of the trunk to follow the direction of the motion that is projected on to the x-y surface will work better, easier to find equilibrium states.

The specific scenario that I tried is script/scenarios/memmo/talos_stairs10_random.py.

Thank you.

**Comment by pFernbach** [comment]
Hi, you are right and actually it was done a few days ago. The modifications still need to be merged in the main branch  : 
https://github.com/humanoid-path-planner/hpp-rbprm-corba/pull/36/

In order to do what you are asking, replace forceOrientation with forveYawOrientation. You need to update hpp-core and hpp-rbprm before updating hpp-rbprm-corba.

**Comment by stonneau** [comment]
I just merged the PR.
